version: 2

models:
  - name: stg_flights
    columns:
      - name: icao24
        data_tests: # 'tests' is now 'data_tests' in modern dbt
          - not_null

      - name: latitude
        data_tests:
          - dbt_utils.accepted_range:
              arguments: # This is the fix for the conversion error
                min_value: -90
                max_value: 90

      - name: speed_kmh
        data_tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
                max_value: 1300