version: 2

models:
  - name: stg_flights
    columns:
      - name: icao24
        data_tests:
          - not_null

      - name: latitude
        data_tests:
          # We use a simple SQL expression to avoid dbt_utils dependency issues for now
          - dbt.expression_is_true:
              expression: "latitude >= -90 AND latitude <= 90"

      - name: speed_kmh
        data_tests:
          - dbt.expression_is_true:
              expression: "speed_kmh >= 0 AND speed_kmh <= 1300"