version: 2
models:
  - name: stg_flights
    columns:
      - name: icao24
        tests:
          - not_null
      - name: latitude
        tests:
          - accepted_values:
              values: range(-90, 90)
      - name: speed_kmh
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1300 # Speed of sound limit for commercial