name: SkyEco Hourly Data Pipeline

on:
  schedule:
    - cron: '0 * * * *' # Runs at the start of every hour
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
  steps:
      - name: "Checkout Code"
        uses: actions/checkout@v6 # <--- Changed from v4 to v6

      - name: "Set up Python"
        uses: actions/setup-python@v6 # <--- Changed from v5 to v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: "Install Dependencies"
        run: |
          pip install -r requirements.txt
          pip install dbt-duckdb==1.9.0 duckdb==1.4.4

      - name: "Step 1: Ingest from Kafka to MotherDuck"
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          KAFKA_BOOTSTRAP: ${{ secrets.KAFKA_BOOTSTRAP }}
          KAFKA_KEY: ${{ secrets.KAFKA_KEY }}
          KAFKA_SECRET: ${{ secrets.KAFKA_SECRET }}
          # Adding these as env vars helps the script find them
          KAFKA_TOPIC: "flights_raw" 
        run: python src/producer.py

      - name: "Step 2: Run dbt Transformations"
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        run: |
          cd dbt
          # Force clean and fresh state
          rm -rf dbt_packages/
          rm -rf target/
          rm -rf dev.duckdb
          dbt deps
          dbt clean
          # Run with --no-partial-parse to ignore the corrupted cache
          dbt run --target dev --no-partial-parse
          dbt test --target dev --no-partial-parse